blank_issues_enabled: true
contact_links:
  - name: Bitcoin Knots Security Policy
    url: https://github.com/bitcoinknots/bitcoin/blob/29.x-knots/SECURITY.md
    about: View security policy
  - name: Bitcoin Knots Developers
    url: https://bitcoinknots.org
    about: Bitcoin Knots homepage
