name: Trigger Inherited CI

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to trigger this manually from the Actions UI

jobs:
  run-bitcoin-ci:
    # Syntax: OWNER/REPOSITORY/PATH@BRANCH
    uses: FlyTheElephant1/bitcoin/.github/workflows/ci.yml@29.x-knots
    
    # Optional: Automatically passes secrets if the inherited workflow requires any
    secrets: inherit 
